# ============================================
# FAN TEMPERATURE CONTROL - TORTOISE HABITAT
# ============================================
# Automatically controls fans based on temperature range

id: 'fan_temperature_control'
alias: "Fan Temperature Control"
description: "Automatically turns fans on and off based on temperature range for tortoise habitat"

trigger:
  # Check every minute to see if fans should be on/off
  - platform: time_pattern
    minutes: '/1'
    id: time_check
  # Trigger when control is enabled to sync current state
  - platform: state
    entity_id: input_boolean.fan_temperature_control_enabled
    to: 'on'
    id: control_enabled
  # Trigger when temperature range changes to sync state
  - platform: state
    entity_id: input_number.fan_temperature_min
    id: min_temp_changed
  - platform: state
    entity_id: input_number.fan_temperature_max
    id: max_temp_changed

condition:
  - condition: state
    entity_id: input_boolean.fan_temperature_control_enabled
    state: 'on'
  - condition: template
    value_template: >
      {% set min_temp = states('input_number.fan_temperature_min') | float(0) %}
      {% set max_temp = states('input_number.fan_temperature_max') | float(0) %}
      {{ min_temp > 0 and max_temp > 0 and max_temp > min_temp }}
  - condition: template
    value_template: >
      {% set temp = state_attr('weather.forecast_home', 'temperature') | float(0) %}
      {% if temp == 0 %}
        {% set temp = state_attr('weather.forecast_home', 'current_temperature') | float(0) %}
      {% endif %}
      {% if temp == 0 %}
        {% set temp = states('weather.forecast_home') | float(0) %}
      {% endif %}
      {{ temp != 0 and temp is not none }}

action:
  - variables:
      min_temp: '{{ states("input_number.fan_temperature_min") | float(60) }}'
      max_temp: '{{ states("input_number.fan_temperature_max") | float(80) }}'
      outdoor_temp: >-
        {% set temp = state_attr('weather.forecast_home', 'temperature') | float(0) %}
        {% if temp == 0 %}
          {% set temp = state_attr('weather.forecast_home', 'current_temperature') | float(0) %}
        {% endif %}
        {% if temp == 0 %}
          {% set temp = states('weather.forecast_home') | float(0) %}
        {% endif %}
        {{ temp }}
      outdoor_temp_available: >-
        {% set temp = state_attr('weather.forecast_home', 'temperature') | float(0) %}
        {% if temp == 0 %}
          {% set temp = state_attr('weather.forecast_home', 'current_temperature') | float(0) %}
        {% endif %}
        {% if temp == 0 %}
          {% set temp = states('weather.forecast_home') | float(0) %}
        {% endif %}
        {{ temp != 0 and temp is not none }}
      fans_should_be_on: >-
        {% if outdoor_temp_available %}
          {{ outdoor_temp >= min_temp and outdoor_temp <= max_temp }}
        {% else %}
          false
        {% endif %}

  - choose:
      # Continuously check and sync fans state (runs every minute)
      - conditions:
          - condition: trigger
            id:
              - time_check
              - control_enabled
              - min_temp_changed
              - max_temp_changed
        sequence:
          - if:
              - condition: template
                value_template: '{{ fans_should_be_on }}'
            then:
              - if:
                  - condition: state
                    entity_id: switch.fans
                    state: 'off'
                then:
                  - service: switch.turn_on
                    target:
                      entity_id: switch.fans
                  - service: system_log.write
                    data:
                      message: 'Fans turned ON (outdoor temp {{ outdoor_temp | round(1) }}°F is within range {{ min_temp }}°F - {{ max_temp }}°F)'
                      level: info
                      logger: tortoise_fan_control
            else:
              - if:
                  - condition: state
                    entity_id: switch.fans
                    state: 'on'
                then:
                  - service: switch.turn_off
                    target:
                      entity_id: switch.fans
                  - service: system_log.write
                    data:
                      message: 'Fans turned OFF (outdoor temp {{ outdoor_temp | round(1) }}°F is outside range {{ min_temp }}°F - {{ max_temp }}°F)'
                      level: info
                      logger: tortoise_fan_control

mode: restart
max: 5

